/*
* # Azure Cosmos DB module
*
* This repository contains our module for creating Cosmos DB resources on Azure. The aim is to provide a simple module, but flexible module that can be used in any Azure environment.
*
* > Note: This module, until version 1.0.0 is considered to be in beta, and breaking changes may occur. Please use with caution.
*
* All requirements and example code is automatically generated by using `terraform-docs`, and this text can be found and updated in the `main.tf` file.
*/
